### ISSUE TITLE
[Feature request] Forum style

### ISSUE THREAD

**Issue by NicoCG** [kmaida/messageboard#3]
Hi @kmaida,

Could you kindly implement the following

Forum (list of discussions) > Topics (list of topics within discussions) > Topic view (View topic)

Currently you have  Topics (list of topics within discussions) > Topic view (View topic)

Please see example for better understanding 
https://popforumsdev.azurewebsites.net/Forums 
https://popforumsdev.azurewebsites.net/Forums/first-test-forum
https://popforumsdev.azurewebsites.net/Forums/Topic/read-this-whats-going-on-in-this-forum

**Comment by kmaida** [comment]
Hi @NicoCG. I'm afraid that right now, I have no plans to build these features as my full-time job takes precedence over free open source projects and I do not have bandwidth available.

Please feel free to implement these features yourself and submit pull requests to incorporate them!
